// Approve Issue - Publish to GitHub
import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/server/db';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  // Note: Authentication should be handled via Clerk middleware
  // This endpoint is protected by middleware.ts auth conditions

  try {
    const { id } = await params;

    // Get issue with feedback
    const issue = await prisma.issue.findUnique({
      where: { id },
      include: { feedback: true },
    });

    if (!issue) {
      return NextResponse.json(
        { error: 'Issue not found' },
        { status: 404 }
      );
    }

    if (issue.status !== 'draft') {
      return NextResponse.json(
        { error: 'Issue is not a draft' },
        { status: 400 }
      );
    }

    // Create issue on GitHub
    const githubResponse = await fetch(
      `https://api.github.com/repos/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}/issues`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${process.env.GITHUB_TOKEN}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: issue.title,
          body: `${issue.body}\n\n---\n*Generated by IterateSwarm*`,
          labels: issue.labels,
        }),
      }
    );

    if (!githubResponse.ok) {
      const error = await githubResponse.text();
      console.error('GitHub API error:', error);
      return NextResponse.json(
        { error: 'Failed to create GitHub issue' },
        { status: githubResponse.status }
      );
    }

    const githubIssue = await githubResponse.json();

    // Update issue status atomically only if still a draft
    const updated = await prisma.issue.updateMany({
      where: {
        id,
        status: 'draft',
      },
      data: {
        status: 'published',
        githubUrl: githubIssue.html_url,
      },
    });

    if (updated.count === 0) {
      return NextResponse.json(
        { error: 'Issue is not a draft or was already processed' },
        { status: 409 }
      );
    }

    return NextResponse.json({
      status: 'published',
      url: githubIssue.html_url,
      issueId: id,
    });
  } catch (error) {
    console.error('Error approving issue:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
