'use server';

import prisma from '@/server/db';
import { revalidatePath } from 'next/cache';

export type IssueWithFeedback = Awaited<ReturnType<typeof getIssue>>;
export type DraftIssue = Awaited<ReturnType<typeof getDrafts>>[number];
export type DashboardStats = Awaited<ReturnType<typeof getDashboardStats>>;

/**
 * Get dashboard statistics for the overview cards
 */
export async function getDashboardStats() {
  try {
    const [pendingFeedback, draftIssues, publishedIssues, rejectedIssues] =
      await Promise.all([
        prisma.feedbackItem.count({ where: { status: 'pending' } }),
        prisma.issue.count({ where: { status: 'draft' } }),
        prisma.issue.count({ where: { status: 'published' } }),
        prisma.issue.count({ where: { status: 'rejected' } }),
      ]);

    return {
      pendingFeedback,
      draftIssues,
      publishedIssues,
      rejectedIssues,
    };
  } catch (error) {
    console.error('Error fetching dashboard stats:', error);
    return {
      pendingFeedback: 0,
      draftIssues: 0,
      publishedIssues: 0,
      rejectedIssues: 0,
    };
  }
}

/**
 * Get all draft issues for the triage page
 */
export async function getDrafts() {
  try {
    const issues = await prisma.issue.findMany({
      where: { status: 'draft' },
      include: {
        feedback: true,
      },
      orderBy: { createdAt: 'desc' },
    });

    return issues;
  } catch (error) {
    console.error('Error fetching drafts:', error);
    return [];
  }
}

/**
 * Get a single issue with its parent feedback content
 */
export async function getIssue(id: string) {
  try {
    const issue = await prisma.issue.findUnique({
      where: { id },
      include: {
        feedback: true,
      },
    });

    return issue;
  } catch (error) {
    console.error('Error fetching issue:', error);
    return null;
  }
}

/**
 * Update an issue's title and body before approving
 */
export async function updateIssue(
  id: string,
  data: { title?: string; body?: string }
) {
  try {
    const issue = await prisma.issue.update({
      where: { id },
      data: {
        title: data.title,
        body: data.body,
      },
    });

    revalidatePath('/issues');
    return { success: true, issue };
  } catch (error) {
    console.error('Error updating issue:', error);
    return { success: false, error: 'Failed to update issue' };
  }
}

/**
 * Approve and publish an issue to GitHub
 */
export async function approveIssue(id: string) {
  try {
    const issue = await prisma.issue.findUnique({
      where: { id },
      include: { feedback: true },
    });

    if (!issue) {
      return { success: false, error: 'Issue not found' };
    }

    if (issue.status !== 'draft') {
      return { success: false, error: 'Issue is not a draft' };
    }

    // Get GitHub config
    const githubOwner = process.env.GITHUB_OWNER;
    const githubRepo = process.env.GITHUB_REPO;
    const githubToken = process.env.GITHUB_TOKEN;

    if (!githubOwner || !githubRepo || !githubToken) {
      // Return mock success for development without GitHub configured
      await prisma.issue.update({
        where: { id },
        data: {
          status: 'published',
          githubUrl: `https://github.com/example/${issue.title.replace(/\s+/g, '-')}`,
        },
      });

      revalidatePath('/issues');
      revalidatePath('/');

      return {
        success: true,
        url: `https://github.com/example/repo/issues/${id}`,
        mock: true,
      };
    }

    // Create issue on GitHub
    const githubResponse = await fetch(
      `https://api.github.com/repos/${githubOwner}/${githubRepo}/issues`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: issue.title,
          body: `${issue.body}\n\n---\n*Generated by IterateSwarm*`,
          labels: issue.labels,
        }),
      }
    );

    if (!githubResponse.ok) {
      const error = await githubResponse.text();
      console.error('GitHub API error:', error);
      return { success: false, error: 'Failed to create GitHub issue' };
    }

    const githubIssue = await githubResponse.json();

    if (!githubIssue.html_url) {
      console.error('GitHub response missing html_url:', githubIssue);
      return { success: false, error: 'Invalid GitHub issue response' };
    }

    // Update issue status
    await prisma.issue.update({
      where: { id },
      data: {
        status: 'published',
        githubUrl: githubIssue.html_url,
      },
    });

    revalidatePath('/issues');
    revalidatePath('/');

    return { success: true, url: githubIssue.html_url };
  } catch (error) {
    console.error('Error approving issue:', error);
    return { success: false, error: 'Failed to approve issue' };
  }
}

/**
 * Reject an issue draft
 */
export async function rejectIssue(id: string, reason?: string) {
  try {
    const issue = await prisma.issue.findUnique({
      where: { id },
    });

    if (!issue) {
      return { success: false, error: 'Issue not found' };
    }

    if (issue.status === 'published') {
      return { success: false, error: 'Cannot reject a published issue' };
    }

    if (issue.status === 'rejected') {
      return { success: false, error: 'Issue is already rejected' };
    }

    const updatedBody = reason
      ? `**Rejected**: ${reason}\n\n---\n\n${issue.body}`
      : issue.body;

    await prisma.issue.update({
      where: { id },
      data: {
        status: 'rejected',
        body: updatedBody,
      },
    });

    revalidatePath('/issues');
    revalidatePath('/');

    return { success: true };
  } catch (error) {
    console.error('Error rejecting issue:', error);
    return { success: false, error: 'Failed to reject issue' };
  }
}

/**
 * Get recent activity for the dashboard
 */
export async function getRecentActivity() {
  try {
    const [feedback, issues] = await Promise.all([
      prisma.feedbackItem.findMany({
        orderBy: { createdAt: 'desc' },
        take: 5,
        include: { issue: true },
      }),
      prisma.issue.findMany({
        where: { status: 'published' },
        orderBy: { updatedAt: 'desc' },
        take: 5,
      }),
    ]);

    return { feedback, publishedIssues: issues };
  } catch (error) {
    console.error('Error fetching recent activity:', error);
    return { feedback: [], publishedIssues: [] };
  }
}
